from __future__ import annotations

from typing import Protocol

import numpy as np


class Controller(Protocol):
    def connect(self) -> bool: ...

    def is_device_online(self) -> bool: ...

    def start_app(self) -> None: ...

    def stop_app(self) -> None: ...

    def screencap(self) -> np.ndarray: ...

    def tap(self, x: int, y: int) -> None: ...

    def keyevent(self, keycode: int) -> None: ...
